# spring.application.name=converter
# server.port=8080

# tesseract.datapath=/opt/homebrew/share/

# spring.data.redis.host=liked-husky-107826.upstash.io
# spring.data.redis.port=6379
# spring.data.redis.password=gQAAAAAAAaUyAAIgcDJiOTMwMDg2YjI5YWU0ZGViYjIzNWE1MThmZWRlOWRiMA
# spring.data.redis.ssl.enabled=true
# spring.data.redis.timeout=6000

spring.application.name=converter
server.port=${PORT:8080}

# ✅ Tesseract (Linux path inside Docker)
tesseract.datapath=${TESSERACT_PATH:/usr/share/tesseract-ocr/4.00/tessdata}

# ✅ Redis
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_REDIS_SSL}
spring.data.redis.timeout=6000