spring.application.name=converter
server.port=8080

tesseract.datapath=/opt/homebrew/share/

spring.data.redis.host=liked-husky-107826.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAaUyAAIgcDJiOTMwMDg2YjI5YWU0ZGViYjIzNWE1MThmZWRlOWRiMA
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=6000